services:
  - type: web
    name: quant-ai-upload
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: IMGBB_API_KEY
        value: 2d18824b2ec85fb015d80e487eb7ab67
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000

